### ISSUE TITLE
Issue with running DRP hidden.

### ISSUE THREAD

**Issue by Protostar909** [jojo2357/Music-Discord-Rich-Presence#5]
Hey, I'm having a strange issue with RunHidden.bat. It claims that DiscordPresenceConfig.ini doesn't exist, when it clearly does. The program works just fine with discord, but it just doesn't like using runHidden. 
![image](https://user-images.githubusercontent.com/38712509/108445701-d7d22b00-722a-11eb-9266-579110827bf4.png)
I definitely have a DiscordPresenceConfig in there.

**Comment by jojo2357** [comment]
hmmm does the shortcut work? I used to run from there but there should be a `runhidden.bat` in `GroovyRP/bin/Release` which is the real one.

**Comment by Protostar909** [comment]
Yeah, that worked! While I've got you, it seems to want to restart randomly, which doesn't make any sense. Discord will just randomly show it running even when groove is closed. The only way to stop it is axing it with task manager or opening groove back up and closing it, and even that only works for a little bit befor DRP fires back up.

**Comment by jojo2357** [comment]
Well sometimes groove starts in the background so the rich presence launches as well. Then, when you open groove, since its already going but comes out of the woodwork, the presence isnt launched either. The rp should close when groove closes provided you have found and linked the two. However, the presence should also work with other players (chrome and spotify) but the auto launching is configured for groove.

**Comment by Protostar909** [comment]
Ahhhh, that makes sense. Thanks!

**Comment by jojo2357** [comment]
If that is all, please close this issue

**Comment by jojo2357** [comment]
The [1.3.0 release](https://github.com/jojo2357/Music-Discord-Rich-Presence/releases/tag/1.3.0) mitigates this issue

**Comment by Protostar909** [comment]
Thanks! This is perfect!
