### ISSUE TITLE
DRP with Discord

### ISSUE THREAD

**Issue by arkiados** [jojo2357/Music-Discord-Rich-Presence#56]
Hello,
Cool project. I'm using groove and discord. I get your batch file running. The program sees grove but I don't know how to link it to the discord app I already use.

Thanks

**Comment by jojo2357** [comment]
I have seen a problem similar to yours where no rich presence shows up. Havent found the cause, but a common fix was to change the default client ID for groove in the config ini. I have prescribed the use of `822184346332168214` to some success in the past, so try that and if that doesnt work lmk.

**Comment by arkiados** [comment]
That worked. Thank you. Next question. It shows up in discord under my name. It says "Playing Groove Music". You have to click on it to see details. Is it possible to have the album and artist displayed instead of "Playing Groove Music"?

**Comment by jojo2357** [comment]
You can sort of do that by keying your albums in such a way that you have an application named that artist, but beyond that it is not possible since you can only have a maximum of 25 apps and even spotify isnt capable of such an integration. Best it can do is configure the presence once you clicked on it (also in the ini). DRP was not designed with such functionality in mind
