### ISSUE TITLE
Local Album Art

### ISSUE THREAD

**Issue by Edison12300** [jojo2357/Music-Discord-Rich-Presence#64]
Hi, is it possible to put local album arts in a folder instead of having to get every image link and add it myself?
I tried the remote option, but it doesn't seem to work. Maybe cause I have mostly japanese songs.
And also I have different album arts even in the same album.
Thanks!

**Comment by jojo2357** [comment]
Local arts: no chance. How would I, another discord user, be able to see it? it has to be a link or an asset in an app so that anyone can access it. I have been to busy, but the idea of the library repo is to automatically resolve those online for you, but I havent gotten around to it.

As for remote, I will test some things to see if I can get Japanese albums to resolve better, but there is no guarantee that this will work with the current API's that I use.

Different arts on the same album is just too much complexity and would make MDRP less reliable overall, so the best I can do is tell you to rename all the albums to singles (if they are local and you can just change metadata) and then key them like that, but I have no plans to add keying individual songs at this time.

**Comment by Smaltin** [comment]
> Maybe cause I have mostly japanese songs.

Could you give me an example of a japanese song that doesn't work with the remote fetch? I'm currently able to fetch all my JP songs just fine, an example or two for reference would help me attempt to solve the issue

**Comment by jojo2357** [comment]
If your experience has improved with 1.7.1 you may close this issue
