### ISSUE TITLE
Rich Presence Fails to Find Album Key On Song Transition in Windows Media Player

### ISSUE THREAD

**Issue by fredjt** [jojo2357/Music-Discord-Rich-Presence#76]
**Version**
The version the bug was found on: 1.7.2

**Describe the bug**
MDRP cannot find any of the album keys until the equalizer is brought up in Windows Media Player on Windows 11 (previously Groove Music). Once the equalizer is brought up (the app seems to do some other things in the background as the song hangs for a second), MDRP finds the album key and everything works, until the song ends and the next one starts. 

**To Reproduce**
1. Open Windows Media Player
2. Open MDRP
3. Play something

**Expected behavior**
MDRP should find the album's key and display its title, the album art, the artist, and the album name in Discord. 

**Screenshots**

Before opening equalizer: 
![image](https://user-images.githubusercontent.com/61065187/197347089-48bd01a7-de2d-4f17-82de-cb25f37e0b66.png)

Opening equalizer:
![image](https://user-images.githubusercontent.com/61065187/197347124-182a5a59-6198-4fe1-8bdf-46af7e363fb6.png)

After opening equalizer:
![image](https://user-images.githubusercontent.com/61065187/197347158-3863f911-83dd-4be7-b686-5ac034efb2fb.png)

**Comment by jojo2357** [comment]
Try enabling the debug missing player setting, disable wmp, and replicate the first half (no details. you may want to replicate the wmp behavior, verify with mdrp, *then* turn off wmp in mdrp). then post that screenshot here. This has been a recurring problem on WMP's side, but let us verify that

**Comment by fredjt** [comment]
This is the message when 'debug missing player' is 'true'. The message flashes briefly about once every two seconds. 
![image](https://user-images.githubusercontent.com/61065187/197375305-115ff9f6-73f9-41e3-a0a2-080b5bc79b2b.png)

This is with 'debug missing player' set to 'true' and 'microsoft.media.player' set to 'false'. The message does not change when I open the equalizer, as expected, so the player stays disabled. 
![image](https://user-images.githubusercontent.com/61065187/197375415-d4543595-83d0-47e2-9759-3f85261f48c1.png)

I think MDRP is correctly identifying the audio player, however, it is having trouble harvesting the necessary data from the player. I was not sure if this was a Microsoft problem or a problem with MDRP. If it is a Microsoft problem, then I can wait for them to update the app and hope that this is one of the many bugs that they decide to get around to fixing.

**Comment by jojo2357** [comment]
Yes, your findings are all consistent with known WMP behavior unfortunately.

Here's the thing, #73 #62 and people in my discord server have had this issue, and we have gone through so much troubleshooting we must have used over two days of manpower. Ultimately I wrote a tool to see **exactly** what MDRP sees and, lo and behold, WMP is not properly reporting its data to Windows Media Center, where MDRP reads from. 

It is a miracle that opening the eq fixes it, because the only other advice that is known besides reinstalling almost everything audio related is to **use a different player** or start changing windows 11 installations because this functionality is known to vary from build to build which is absolutely ridiculous . 

You should try playing a youtube video while wmp is enabled and playing audio. You will find that MDRP will pick up your youtube video because WMP **fails to report what it is playing to WMC, despite them being made by the same company**

Here is a crappy graphic I made to illustrate the root of the issue a while back
<img src="https://cdn.discordapp.com/attachments/817660732334276631/1007383862990602332/WMP_bad.png">

Also, I would like to remind those keeping score at home that there were very few issues with Groove in Windows 10. Then MS came and changed it all and here we are.

Leaving this open because idk what to do with it

**Comment by fredjt** [comment]
Yes, Microsoft was just finally working out the last of the major bugs in Groove music when they abandoned it for a reboot of WMP. I do wish they had just kept working on making Groove work properly. Thank you for your help with this issue! Hopefully Microsoft will get around to fixing this issue soon, as I do kind of miss the old WMC from Windows 10.

**Comment by jojo2357** [comment]
Of course! hope it works itself out

**Comment by jojo2357** [comment]
Please don't take the pin the wrong way. You documented your issue very well, others are having it as well, and it cannot be fixed here, so hopefully I will get less of these. Thanks again.
